const express = require("express");
const routes = express.Router();
const {Auth} = require("../middlewares");
const StudentControllers = require("../controllers/student.controller");
routes.get("/all",  StudentControllers.getAllStudent);
routes.get("/", Auth, StudentControllers.getStudentById);
routes.post("/", StudentControllers.createStudent);
routes.put("/:id",  StudentControllers.updateStudent);
routes.delete("/:id",  StudentControllers.deleteStudent);
module.exports = routes;
